### ISSUE TITLE
Manifestoo could be use to list all distributed modules for a given Odoo installation

### ISSUE THREAD

**Issue by xtof-osd** [sbidoul/manifestoo#17]
As it is possible to use addons_path from odoo.conf, Manifestoo could provide a command line option to liste all distributed modules.
This can be useful for auditing an complete installation.

**Comment by sbidoul** [comment]
Sounds like a good idea. It could be done with a new [--select option](https://manifestoo.readthedocs.io/en/stable/addons_selection.html).

Do you want to try doing a PR?

**Comment by xtof-osd** [comment]
I will first get familiar with the code. I also aim at looking if it's a good idea to integrate some features from another scripts of mine that produce graphml for Odoo dependencies.

**Comment by sbidoul** [comment]
> produce graphml for Odoo dependencies

Could be in interesting complement to `manifestoo tree`. Could you post screenshots in a separate issue to discuss that possibility ?
